services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecret
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: blog_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL = postgresql://postgres:mysecret@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:mysecret@postgres:5432/postgres

volumes:
  postgres_data:
