name: Continous Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.Docker_USERNAME}}
          password: ${{secrets.Docker_PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/blog:${{github.sha}}
          build-args: |
            DATABASE_URL=${{ secrets.VM_DATABASE_URL }}

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_OS }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.Docker_USERNAME }}/blog:${{github.sha}}
            sudo docker stop blog || true
            sudo docker rm blog || true
            sudo docker run -d \
              --name blog \
              -p 80:3000 \
              -e DATABASE_URL=${{ secrets.VM_DATABASE_URL }} \
              ${{ secrets.Docker_USERNAME }}/blog:${{ github.sha }}
