name: Continous Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.Docker_USERNAME}}
          password: ${{secrets.Docker_PASSWORD}}

      - name: Build and push docker image
        run: |
          docker compose build
          docker tag $(docker compose images -q app) ${{ secrets.Docker_USERNAME }}/blogapplication:latest
          docker push ${{ secrets.Docker_USERNAME }}/blogapplication:latest

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_OS }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/blogapplication:latest
            DATABASE_URL=${{ secrets.VM_DATABASE_URL }} docker compose up -d --build
